- name : Initial Cluster
  hosts: localhost
  tasks:
    - include_tasks: create-instance.yml
      vars:
        gcp_project: <project-id>
        gcp_cred_kind: serviceaccount
        gcp_cred_file: ansible.json
        credentials_file: key.pub
        zone: "us-central1-a"
        region: "us-central1"
      loop:
        - vm-1
        - vm-2
